config/routes.rb
Rails.application.routes.draw do
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy] 
  def index
    @books=Book.all
  end
  
  def show
    
  end
  
  def edit
    
  end
  
  def new
    @book=Book.new
  end
  
  def create
    @book=Book.new(clean_data)
    if @book.save
      redirect_to books_path, notice: "新增成功!"      
    else
      render 'new'
    end
  end
  
  def update
        
    if @book.update(clean_data)
      redirect_to books_path, notice: "更新成功!"
    else
      render 'edit'
    end
  end
  
  def destroy
    
    @book.destroy
    redirect_to books_path, notice: "刪除成功!"
  end
  
  private
    def clean_data
      params.require("book").permit(:name, :intro, :author, :price)
    end
  end
  
  def find_book
    @book=Book.find_by(id: params[:id])
    if @book.nil?
      redirect_to books_path, notice: "沒有資料!"
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
  def ntd(book)
    "新台幣$#{book.price}"
  end
end

app/views/books/_form.html.erb
<%= form_for book do |f| %>
  書名:<%= f.text_field :name %><br />
  簡介:<%= f.text_area :intro %><br />
  作者:<%= f.text_field :author %><br />
  價錢:<%= f.text_field :price %><br />
  <%= f.submit %>
<%=link_to "返回" ,books_path %>
<% end %>

app/views/books/edit.html.erb
<h1>編輯頁面</h1>
<%= render 'form' ,book: @book %>

app/views/books/index.html.erb
<%= notice %>
<h1>書本列表</h1>
<table>
  <thead>
    <tr>
      <td>書名</td>
      <td>簡介</td>
      <td>作者</td>
      <td>價錢</td>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.intro %></td>
        <td><%= book.author %></td>
        <td><%= ntd(book) %></td>
        <td><%= link_to "查閱",book %></td>
        <td><%= link_to "編輯",edit_book_path(book) %></td>
        <td><%= link_to "刪除",book ,method: "delete", data: { confirm: '確定要刪除?' } %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>
<%= link_to "新增書籍",new_book_path %>

app/views/books/new.html.erb
<h1>新增書籍</h1>
<%= render "form" ,book: @book %>

app/views/books/show.html.erb
<h1>查閱書籍</h1>
書名:<td><%=@book.name %></td><br />
簡介:<td><%=@book.intro %></td><br />
作者:<td><%=@book.author %></td><br />
價錢:<td><%=ntd(@book) %></td><br />
<%=link_to "返回" ,books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>